export type { PlanInput, SimulationResult, YearSnapshot, LifeEvent, Child, ScenarioOverride, PlanDocument } from './types'
export { SCHEMA_VERSION } from './types'
export { createDefaultPlan, createLifeEvent, createChild, DEFAULT_UNIVERSITY_TOTAL, UNIVERSITY_START_AGE } from './defaults'
export { simulate, applyOverrides } from './simulate'
export { validatePlan } from './validate'
export type { ValidationIssue } from './validate'
export { exportPlan, downloadPlanJson, importPlanJson } from './serialize'
export type { ImportResult, ImportError } from './serialize'
